export const opacityAnimation: string;
export const server: string;
export const serverBtns: string;
export const serverDesc: string;
export const serverInfo: string;
export const serverInfoText: string;
export const serverLogo: string;
export const serverLogoImg: string;
export const serverTitle: string;
